# CI Script for GitLab CI

stages:
  - build
  - test

build:
  stage: build
  image: node:24-alpine
  rules:
    - changes:
        paths:
          - 'dist/**'
          - 'src/**'
          - .gitlab-ci.yml
  before_script:
    - apk add --no-cache git
    - git config --global user.name "$GITLAB_USER_NAME"
    - git config --global user.email "$GITLAB_USER_EMAIL"
    - git checkout "$CI_COMMIT_REF_NAME"
  script:
    - npm ci
    - npm run build:github
    - npm run build:gitlab
    - |
      if [ -n "$(git status --porcelain)" ]; then
        git add .
        git commit -m "[ci skip] updated by CI build"
        git push -f origin HEAD:$CI_COMMIT_REF_NAME
      else
        echo "no change after build"
      fi
  artifacts:
    paths:
      - dist/**

test-1:
  stage: test
  image: node:24-alpine
  rules:
    - changes:
        paths:
          - dist/**
          - src/**
          - test/**
          - .gitlab-ci.yml
  variables:
    INPUT_INPUT: test/1_in*.csv
    INPUT_OUTPUT: test/1_out*.csv
    INPUT_COLUMNS: "2"
    INPUT_SOURCE: "1"
  before_script:
    - apk add --no-cache diffutils
  script:
    - node dist/gitlab/index.js
    - if [ ! -f test/1_output.csv ]; then echo "Produced CSV not found" && exit 2; fi
    - diff -u test/1_output_expected.csv test/1_output.csv || (echo "CSV mismatch" && exit 1)

test-2:
  stage: test
  image: node:24-alpine
  rules:
    - changes:
        paths:
          - dist/**
          - src/**
          - test/**
          - .gitlab-ci.yml
  variables:
    INPUT_INPUT: test/2_in*.csv
    INPUT_OUTPUT: test/2_out*.csv
    INPUT_COLUMNS: "1,2"
    INPUT_SOURCE: "0"
    INPUT_HEADER: false
    INPUT_ENCODING: utf8
    INPUT_UTF_BOM: true
    INPUT_LINEFEED: LF
    INPUT_SEPARATOR: ","
    INPUT_QUOTE_ALWAYS: false
  before_script:
    - apk add --no-cache diffutils
  script:
    - node dist/gitlab/index.js
    - if [ ! -f test/2_output.csv ]; then echo "Produced CSV not found" && exit 2; fi
    - diff -u test/2_output_expected.csv test/2_output.csv || (echo "CSV mismatch" && exit 1)

test-cli-1:
  stage: test
  image: node:24-alpine
  rules:
    - changes:
        paths:
          - dist/**
          - src/**
          - test/**
          - .gitlab-ci.yml
  before_script:
    - apk add --no-cache diffutils
  script:
    - node dist/index.js --input test/1_in*.csv --output test/1_out*.csv --columns 2 --source 1
    - if [ ! -f test/1_output.csv ]; then echo "Produced CSV not found" && exit 2; fi
    - diff -u test/1_output_expected.csv test/1_output.csv || (echo "CSV mismatch" && exit 1)

test-cli-2:
  stage: test
  image: node:24-alpine
  rules:
    - changes:
        paths:
          - dist/**
          - src/**
          - test/**
          - .gitlab-ci.yml
  before_script:
    - apk add --no-cache diffutils
  script:
    - node dist/index.js --input test/2_in*.csv --output test/2_out*.csv --columns "1,2" --source 0 --no-header --encoding utf8 --utf-bom --linefeed LF --separator "," --quote-always
    - if [ ! -f test/1_output.csv ]; then echo "Produced CSV not found" && exit 2; fi
    - diff -u test/1_output_expected.csv test/1_output.csv || (echo "CSV mismatch" && exit 1)
