name: Append line numbers to CSV
description: add numbers to the certain columns in a CSV file
author: h1data

inputs:
  input:
    description: Input file path
    required: true
  output:
    description: Output file path
    required: true
  columns:
    description: Specifies the columns by number to add line numbers (starts with 0, separated by comma if multiple)
    required: true
  source: 
    description: Specifies the column number of the source text for filling if target columns are empty (starts with 0)
  header:
    description: Whether the CSV has header (true/false)
    required: false
    default: "true"
  encoding:
    description: Specifies encoding
    required: false
    default: "utf8"
  linefeed:
    description: Specifies linefeed (CRLF/LF)
    required: false
    default: "CRLF"
  separator:
    description: Specifies the separator of columns
    required: false
    default: ","
  escape:
    description: Specifies escape character for separators
    required: false
    default: "\""
  quote-always:
    description: Whether if always quote (true/false)
    required: false
    default: "false"

outputs:
  output:
    description: Output file path
  lines:
    description: The number of lines in the CSV file excluding the header

runs:
  using: node24-slim
  main: "dist/github/index.js"
